// general
export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER';
export const CLEAR_AUTHENTICATED_USER = 'CLEAR_AUTHENTICATED_USER';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';


